
import React from 'react';

export const TRANSLATIONS = {
  en: {
    welcome: "Welcome to your Farm Helper",
    tagline: "I help you grow better crops.",
    getStarted: "Start Now",
    languageSelect: "Pick your language",
    locationSelect: "Where is your farm?",
    fieldDetails: "About your farm",
    soilType: "Soil Type",
    waterSource: "Water Source",
    acres: "Acres",
    next: "Next",
    finish: "Finish Setup",
    dashboard: "My Farm",
    diagnosis: "Crop Doctor",
    planner: "Farm Plan",
    encyclopedia: "Farming Info",
    profile: "My Profile",
    askAnything: "Ask me a farm question...",
    sow: "Planting",
    irrigate: "Watering",
    apply: "Fertilizer",
    warning: "Alert",
    healthScore: "Health Score",
    recommendation: "Advice",
    home: "Home",
    trends: "Best Crops",
    manage: "Daily Work",
    wiki: "Library",
    intelligence: "Smart Tips",
    realTime: "Live Info",
    marketPulse: "Market Price",
    soilMoisture: "Soil Wetness",
    ambientTemp: "Outside Temp",
    soilPh: "Soil pH",
    nitrogen: "Nitrogen",
    reasoningCore: "AI Helper",
    strategicIntel: "Smart Tips",
    weeklyForecast: "7-Day Weather",
    operationalProtocol: "How to do work",
    pestsDatabase: "Bugs & Disease",
    profitPerformance: "Money Report",
    optimizationEngine: "Crop Helper",
    soilProfile: "Soil Details",
    lockProfile: "Save Profile",
    editProfile: "Change Profile",
    precisionAgronomy: "Expert Tips",
    nutritionalJourney: "Food for Crops",
    profitBooster: "Make More Money",
    nutrientStrategy: "Fertilizer Plan",
    organicWealth: "Natural Farming",
    technicalBlueprint: "Step-by-Step Plan",
    applyToField: "Apply Now",
    deepAnalysis: "Full Details",
    resilience: "Strength",
    inputCost: "Money to Spend",
    marketSell: "Mandi Price",
    harvesting: "Harvest Time",
    mainRisk: "Main Risk",
    stop: "Stop",
    expand: "Bigger",
    minimize: "Smaller",
    login: "Login",
    email: "Email",
    password: "Password",
    signIn: "Sign In",
    forgotPassword: "Forgot Password?",
    welcomeBack: "Welcome Back",
    noAccount: "New? Join here",
    rememberMe: "Stay Logged In",
    secureGateway: "Farmer Entrance",
    brandMotto: "Helping you grow better crops with simple AI advice."
  },
  hi: {
    welcome: "समर्थ किसान में आपका स्वागत है",
    tagline: "आपका डिजिटल फार्म सह-पायलट",
    getStarted: "शुरू करें",
    languageSelect: "अपनी भाषा चुनें",
    locationSelect: "आपका खेत कहाँ है?",
    fieldDetails: "अपने खेत के बारे में बताएं",
    soilType: "मिट्टी का प्रकार",
    waterSource: "पानी का स्रोत",
    acres: "एकड़",
    next: "अगला",
    finish: "सेटअप पूरा करें",
    dashboard: "डैशबोर्ड",
    diagnosis: "निदान",
    planner: "फार्म प्लानर",
    encyclopedia: "ज्ञान",
    profile: "प्रोफाइल",
    askAnything: "समर्थ किसान से कुछ भी पूछें...",
    sow: "बुवाई",
    irrigate: "सिंचाई करें",
    apply: "उर्वरक डालें",
    warning: "कार्रवाई आवश्यक",
    healthScore: "स्वास्थ्य स्कोर",
    recommendation: "सिफारिशें",
    home: "होम",
    trends: "रुझान",
    manage: "प्रबंधन",
    wiki: "विकिपीडिया",
    intelligence: "इंटेलिजेंस",
    realTime: "रियल-टाइम",
    marketPulse: "लाइव मार्केट पल्स",
    soilMoisture: "मिट्टी की नमी",
    ambientTemp: "तापमान",
    soilPh: "मिट्टी का पीएच",
    nitrogen: "नाइट्रोजन",
    reasoningCore: "लाइव एआई रीजनिंग कोर",
    strategicIntel: "रणनीतिक बुद्धिमत्ता",
    weeklyForecast: "साप्ताहिक पूर्वानुमान",
    operationalProtocol: "परिचालन प्रोटोकॉल",
    pestsDatabase: "कीट डेटाबेस",
    profitPerformance: "लाभ प्रदर्शन",
    optimizationEngine: "फसल अनुकूलन इंजन",
    soilProfile: "मिट्टी का विवरण",
    lockProfile: "प्रोफ़ाइल लॉक करें",
    editProfile: "प्रोफ़ाइल बदलें",
    precisionAgronomy: "सटीక कृषि एआई",
    nutritionalJourney: "पोषण यात्रा",
    profitBooster: "लाभ बूस्टर",
    nutrientStrategy: "पोषक तत्व रणनीति",
    organicWealth: "जैविक धन रणनीति",
    technicalBlueprint: "तकनीकी खाका",
    applyToField: "खेत पर लागू करें",
    deepAnalysis: "गहरा विश्लेषण",
    resilience: "लचीलापन",
    inputCost: "लागत",
    marketSell: "बाजार मूल्य",
    harvestिंग: "कटाई",
    mainRisk: "मुख्य जोखिम",
    stop: "रोकें",
    expand: "बड़ा करें",
    minimize: "छोटा करें",
    login: "लॉगिन",
    email: "ईमेल पता",
    password: "पासवर्ड",
    signIn: "सुरक्षित साइन इन",
    forgotPassword: "पासवर्ड भूल गए?",
    welcomeBack: "आपका स्वागत है",
    noAccount: "नए हैं? खाता बनाएं",
    rememberMe: "साइन इन रहें",
    secureGateway: "सुरक्षित कृषि प्रवेश द्वार",
    brandMotto: "मिट्टी और उच्च-कंप्यूट बुद्धिमत्ता के बीच की खाई को पाटना।"
  },
  te: {
    welcome: "సమర్థ్ కిసాన్‌కు స్వాగతం",
    tagline: "మీ డిజిటల్ ఫార్మ్ కో-పైలట్",
    getStarted: "మొదలుపెట్టండి",
    languageSelect: "మీ భాషను ఎంచుకోండి",
    locationSelect: "మీ పొలం ఎక్కడ ఉంది?",
    fieldDetails: "మీ పొలం గురించి మాకు చెప్పండి",
    soilType: "నేల రకం",
    waterSource: "నీటి వనరు",
    acres: "ఎకరాలు",
    next: "తదుపరి",
    finish: "సెటప్ పూర్తి చేయండి",
    dashboard: "డాష్‌బోర్డ్",
    diagnosis: "రోగనిర్ధారణ",
    planner: "ఫార్మ్ ప్లానర్",
    encyclopedia: "జ్ఞానం",
    profile: "ప్రొఫైల్",
    askAnything: "సమర్థ్ కిసాన్‌ను ఏదైనా అడగండి...",
    sow: "విత్తండి",
    irrigate: "నీరు పెట్టండి",
    apply: "ఎరువులు వేయండి",
    warning: "చర్య అవసరం",
    healthScore: "ఆరోగ్య స్కోరు",
    recommendation: "సిఫార్సులు",
    home: "హోమ్",
    trends: "ట్రెండ్స్",
    manage: "నిర్వహణ",
    wiki: "వికీ",
    intelligence: "ఇంటెలిజెన్స్",
    realTime: "రియల్-టైమ్",
    marketPulse: "లైవ్ మార్కెట్ పల్స్",
    soilMoisture: "నేల తేమ",
    ambientTemp: "ఉష్ణోగ్రత",
    soilPh: "నేల pH",
    nitrogen: "నైట్రోజన్",
    reasoningCore: "లైవ్ AI రీజనింగ్",
    strategicIntel: "వ్యూహాత్మక సమాచారం",
    weeklyForecast: "వారపు అంచనా",
    operationalProtocol: "ఆపరేషనల్ ప్రోటోకాల్",
    pestsDatabase: "కీటకాల సమాచారం",
    profitPerformance: "లాభదాయకత",
    optimizationEngine: "పంట ఆప్టిమైజేషన్",
    soilProfile: "నేల ప్రొఫైల్",
    lockProfile: "ప్రొఫైల్ లాక్",
    editProfile: "ప్రొఫైల్ సవరించు",
    precisionAgronomy: "ప్రెసిషన్ అగ్రోనమీ AI",
    nutritionalJourney: "పోషణ ప్రయాణం",
    profitBooster: "లాభాల బూస్టర్",
    nutrientStrategy: "పోషక వ్యూహం",
    organicWealth: "సేంద్రియ సంపద వ్యూహం",
    technicalBlueprint: "టెక్నికల్ బ్లూప్రింట్",
    applyToField: "పొలానికి వర్తింపజేయి",
    deepAnalysis: "లోతైన విశ్లేషణ",
    resilience: "తట్టుకునే శక్తి",
    inputCost: "పెట్టుబడి ఖర్చు",
    marketSell: "మార్కెట్ ధర",
    harvesting: "కోత",
    mainRisk: "ప్రధాన ముప్పు",
    stop: "ఆపండి",
    expand: "పెద్దది చేయి",
    minimize: "చిన్నది చేయి",
    login: "లాగిన్",
    email: "ఈమెయిల్ చిరునామా",
    password: "పాస్వర్డ్",
    signIn: "సురక్షిత లాగిన్",
    forgotPassword: "పాస్వర్డ్ మర్చిపోయారా?",
    welcomeBack: "తిరిగి స్వాగతం",
    noAccount: "కొత్తవారా? ఖాతా సృష్టించండి",
    rememberMe: "సైన్ ఇన్ అయి ఉండండి",
    secureGateway: "సురక్షిత వ్యవసాయ ద్వారం",
    brandMotto: "నేల మరియు హై-కంప్యూట్ మేధస్సు మధ్య అంతరాన్ని తగ్గించడం."
  }
};

export const CROP_TYPES = ["Wheat", "Rice", "Tomato", "Cotton", "Maize", "Sugarcane"];
export const SOIL_TYPES = ["Alluvial", "Black", "Red", "Laterite", "Sandy"];
export const WATER_SOURCES = ["Well", "Canal", "Rainfed", "Borewell", "Drip"];
